### PR TITLE
Update to 0.8

### PR DESCRIPTION
**Pull request by chachi**

### CODE REVIEW

**Comment by fstanley** [comment]
Thanks, worked for me

**Comment by krader1961** [comment]
Ping? Has this project been abandoned? The IWYU 0.7 release is now 2.5 years old. The current release is 0.12. So even this PR is so old as to be irrelevant.

**Comment by jasonmp85** [comment]
> Ping? Has this project been abandoned? The IWYU 0.7 release is now 2.5 years old. The current release is 0.12. So even this PR is so old as to be irrelevant

No, but I've mostly abandoned packaging IWYU in this way; it breaks too often. I've bugged upstream for a few fixes here and there; possibly I'll get some time soon to look into whether they help.

**Comment by jasonmp85** [comment]
Woah, yeah upstream actually removed their prebuilt binaries. But… I think the issue keeping me from just asking for inclusion in Homebrew proper might be solved now? Was able to build locally just using the `llvm` package from Homebrew (previously this was very fragile and didn't include necessary headers, making an LLVM build necessary, which was unacceptable).

**Comment by krader1961** [comment]
@jasonmp85 Thanks for responding. I've been working on keeping ksh (the Korn Shell) [project](https://github.com/att/ast/) alive. An important part of that work is normalizing the source style and cleaning up #include's. Up until recently I found the Homebrew IWYU tool useful. Then, apparently because I updated LLVM, it started ignoring my map file and thus began telling me to make stupid changes like replace `#include <fcntl.h>` with `#include <sys/fcntl.h>`.

**Comment by jasonmp85** [comment]
@krader1961 Yeah… I mostly started this project for my own convenience after Homebrew upstream rejected my initial formula due to its brittleness (they were right).

Within my own team, another member was adamantly against automated include processing (I… don't really understand why? (hi @anarazel!)), buuuut I may pick it up again soon for some module/code complexity analysis purposes.

I think I can get this upstream now which would at least push it off onto the broader Homebrew community, both for increased usage and for better distribution of maintainer responsibilities.

Closing this issue for now, since—as you noted—this is so obsolete IWYU is not even one or two releases from it (more like four) and besides, there is no longer a Darwin prebuilt so my whole approach is defunct.

**Comment by jasonmp85** [comment]
OK, so I was correct that this would be accepted upstream; I went to look into doing so today and… someone else already did it 29 days ago!

Just use the `homebrew-core` version of this software from now on (hooray!)

**Pull request closed without merging**
