### PR TITLE
Symlink include files so C++ header files are found

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by jasonmp85** [comment]
Hey, sorry; just got around to looking at this (I tend to put it off until something breaks for me. Bad, I know).

Can you provide a quick test case to exercise this functionality (presumably something that breaks before your change but is fixed after)? I'll merge it and release a 0.4.1 if so.

I'm about to release a 0.5 with "LLVM 7.0.0" (El Cap/Xcode 7.0) support, so want to get this into the current 0.4.x master release before I move onto a higher version number.

**Comment by MikaelSmith** [comment]
Using github.com/puppetlabs/leatherman, I was doing `iwyu -Xiwyu --verbose=2 -DBOOST_ALL_DYN_LINK -DBOOST_LOG_WITHOUT_WCHAR_T -DUSE_JRUBY_SUPPORT -DUSE_OPENSSL -DUSE_YAMLCPP -O3 -DNDEBUG -Ilocale/inc -I/usr/local/include     -std=c++11 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-tautological-constant-out-of-range-compare -Wno-deprecated-register  -c locale/src/posix/locale.cc`, with the result

```
In file included from locale/src/posix/locale.cc:1:
locale/inc/leatherman/locale/locale.hpp:6:10: fatal error: 'locale' file not found
#include <locale>
         ^

(locale/inc/leatherman/locale/locale.hpp has correct #includes/fwd-decls)

(locale/src/posix/locale.cc has correct #includes/fwd-decls)
```

`iwyu` was unable to find any headers from the standard library, because they're implicit in the compile command. Linking iwyu's include directory to the install location from Xcode fixes that.

**Comment by MikaelSmith** [comment]
I still run into a problem finding system headers like `stdarg.h`, not sure why that's happening now.

**Comment by jasonmp85** [comment]
That's an El Cap problem. The header files changed locations, so they're not in `"#{MacOS::Xcode.toolchain_path}/usr/lib/clang/6.1.0"` anymore but rather `"#{MacOS::Xcode.toolchain_path}/usr/lib/clang/7.0"`…

It's annoying that this breaks every time a new Xcode is installed, but the alternative appears to be depending upon LLVM with Clang support. The Homebrew `llvm` package doesn't have clang support, so it won't install from a bottle, and an LLVM source build takes so long in e.g. Travis that I can't do CI.

So I have been doing this shortcut of "link to the clang headers within Xcode", with the caveat that I have to release a new IWYU version each time Clang is bumped, which honestly is pretty much the level of usability the upstream project provides anyhow.

Anyways, thanks for the pointer to a real-world C++ header; I'm a C coder so don't know what headers are even in that directory, just wanted an example to throw in my test.

I'll merge this (and add a test), release as 0.4.1 for people still on Clang 3.6 (or 6.0 in Apple's parlance) and fix the 7.0/El Cap issues, releasing that as 0.5.0. Then a brew upgrade should take care of you, assuming you're on El Cap (otherwise you'll want to manually stay on 0.4.1).

Thanks for the quick reply!

**Comment by MikaelSmith** [comment]
Great, thanks!

**Comment by jasonmp85** [comment]
Ugh. Well, that took longer than expected.

I added a matrix build to travis to test on three clang versions (the highest supported by the last three OS X versions), and discovered that the `include` and `lib` directories in the project folder get linked (in `/usr/local`) and GCC adds a `c++` directory in `/usr/local/include` (or something, I forget) which collides with the `c++` directory added here.

Since `iwyu` doesn't actually need to _expose_ these `include` and `lib` directories to the outside world (but needs them itself due to the insane "libclang expects builtin headers relative to the produced binaries" restrictions), I decided to move everything into an internal `iwyu` folder and then only link the bins for installation.

Passes on clang 6.1, 6.4, and 7.0 in Travis.

**Pull request closed without merging**
